package pgr209.Lecture2.Yahtzee;

public enum Category {

    ONES, TWOS, THREES, FOURS, FIVES, SIXES,

    PAIR, TWO_PAIRS, THREE_OF_A_KIND, FOUR_OF_A_KIND,

    SMALL_STRAIGHT, LARGE_STRAIGHT, FULL_HOUSE,

    YAHTZEE, CHANCE

}
